pipeline {
    agent {
        docker {
            image 'img.ones.pro/global/tools-centos:0.2'
        }
    }
    environment {
        REPO_NAME = "open-docs"
        // REPO_OWNER = "github.com/BangWork"
        // BUCKET = "ones-com-developer-static"
    }
    options {
        timeout(time: 300, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Check input') {
            steps {
                sh '''
                    if [ -z ${DOCS_RELEASE_TAG} ]; then
                        echo "Please input a release tag"
                        exit 1
                    fi
                '''
            }
        }
        stage('Get release') {
            steps {
                withCredentials(
                    bindings: [usernamePassword(credentialsId: 'web_github_token', \
                    usernameVariable: 'GITHUB_USER', \
                    passwordVariable: 'GITHUB_ACCESS_TOKEN')
                    ]) {
                    sh '''
                        python3 devops/release/download_release_asset.py ${GITHUB_ACCESS_TOKEN} BangWork/${REPO_NAME} ${DOCS_RELEASE_TAG} ./
                        rm -rf ${REPO_NAME} && mkdir ${REPO_NAME}
                        tar -zxf ${REPO_NAME}-${DOCS_RELEASE_TAG}.tar.gz -C ${REPO_NAME}
                        ls ${REPO_NAME}
                    '''
                }
            }
        }
        stage('Upload to S3') {
            steps {
                withCredentials([
                    string(credentialsId: 's3-open-docs-id', variable: 'AWS_ID_VALUE'),
                    string(credentialsId: 's3-open-docs-key', variable: 'AWS_KEY_VALUE')
                ]) {
                    sh '''
                        mc config host add mys3 https://s3.amazonaws.com ${AWS_ID_VALUE} ${AWS_KEY_VALUE}
                        mc mirror --remove --overwrite ${REPO_NAME} mys3/${BUCKET}/
                    '''
                }
            }
        }
    }
  post {
    always {
      echo 'Pipeline finished, Pushing notification now....'
    }
  }
}

