openapi: 3.0.1
info:
  title: Summary mode issue worklog
  version: '1.0'
  description: |
    This resource represents issue worklog in summary mode. Use it to get, create, update, and delete issue worklog.
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /project/issues/{issueID}/workLog/summary/timesEstimated:
    post:
      summary: Add Estimated time in summary mode
      operationId: 01-add-estimated-time-of-issues
      description: Add Estimated time in summary mode.
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Add estimated time in summary mode.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTimesEstimatedRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTimesEstimatedResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/issues/{issueID}/workLog/summary/timesEstimated/{timesEstimatedID}:
    put:
      summary: Update estimated time in summary mode
      operationId: 02-update-estimated-time-of-issues
      description: Update estimated time in summary mode.
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesEstimatedID
          in: path
          description: The timesEstimated ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Update estimated time in summary mode.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTimesEstimatedRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTimesEstimatedResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
    delete:
      summary: Delete estimated time in summary mode
      operationId: 03-delete-estimated-time-of-issues
      description: Delete estimated time in summary mode.
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesEstimatedID
          in: path
          description: The timesEstimated ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTimesEstimatedResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/issues/{issueID}/workLog/summary/timesSpent:
    get:
      summary: Get a list of issues worklog in summary mode
      operationId: 04-get-a-list-of-issues-worklog
      description: Get a list of issues worklog in summary mode.
      security:
        - oauth2:
            - read:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: The number of test case libraries returned by this request.
          schema:
            type: integer
        - name: cursor
          in: query
          description: The starting location of this request.
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesSpentListResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
    post:
      summary: Add spent times in summary mode
      operationId: 05-add-spent-time-of-issues
      description: Add spent times in summary mode.
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Add spent times to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTimesSpentRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTimesSpentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/issues/{issueID}/workLog/summary/timesSpent/{timesSpentID}:
    put:
      summary: Update spent times in summary mode
      operationId: 06-update-spent-time-of-issues
      description: Update spent times in summary mode.
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: The timesSpent ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Update spent times to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTimesSpentRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTimesSpentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
    delete:
      summary: Delete spent times in summary mode
      operationId: 07-delete-spent-time-of-issues
      description: Delete spent times in summary mode.
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: The timesSpent ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTimesSpentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
    get:
      summary: Get a spent times in summary mode
      operationId: 08-get-spent-time-of-issues
      description: Get a spent times in summary mode.
      security:
        - oauth2:
            - read:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: The ID of the team.
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: The timesSpent ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTimesSpentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    GetTimesSpentResponse:
      description: 'The result of get a spent time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        data:
          type: object
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
    DeleteTimesSpentResponse:
      description: 'The result of delete spent time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
    UpdateTimesSpentRequest:
      description: 'The request of update spent time'
      type: object
      properties:
        hours:
          type: integer
          description: The spent time.
        description:
          type: string
          description: The description of spent time.
        startTime:
          type: integer
          description: The start time of spent time.
        owner:
          type: object
          description: The owner of spent time.
      example:
        hours: 1
        description: 'Sample Description'
        startTime: 1689055200
        owner: UWQR89ji
    UpdateTimesSpentResponse:
      description: 'The result of update spent time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        data:
          type: object
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
    AddTimesSpentRequest:
      description: 'The request of add spent time'
      type: object
      properties:
        hours:
          type: integer
          description: The spent time.
        description:
          type: string
          description: The description of spent time.
        startTime:
          type: integer
          description: The start time of spent time.
        owner:
          type: object
          description: The owner of spent time.
      example:
        hours: 1
        description: 'Sample Description'
        startTime: 1689055200
        owner: UWQR89ji
    AddTimesSpentResponse:
      description: 'The result of add spent time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        data:
          type: object
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
    TimesSpentListResponse:
      description: 'The result of estimated time.'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        data:
          type: object
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
          data:
            list:
              - description: 'Sample Description 1'
                hours: 1
                owner:
                  id: 'xx'
                  name: 'xx'
                startTime: 1689055200
              - description: 'Sample Description 2'
                hours: 2
                owner:
                  id: 'yy'
                  name: 'yy'
                startTime: 1689055300
            pageInfo:
              count: 2
              endCursor: 'sample_end_cursor'
              hasNextPage: false
              startCursor: 'sample_start_cursor'
              totalCount: 2
    AddTimesEstimatedRequest:
      description: 'The request of add estimated time'
      type: object
      properties:
        hours:
          type: integer
          description: Estimated time,unit is hour.
        startDate:
          type: string
          description: The start time of spent time,Format is YYYY-MM-DD.
        endDate:
          type: string
          description: The end time of spent time,Format is YYYY-MM-DD.
        owner:
          type: object
          description: The owner of spent time.
        includeNonWorkingDays:
          type: boolean
          description: Whether to include non-working days.
        timesEstimatedMode:
          type: string
          enum:
            - total
            - daily
          description: |
            - total: Total estimated time from start date to end date.
            - daily: Estimated time per day from start date to end date.
      example:
        hours: 1
        startDate: '2023-01-01'
        endDate: '2023-01-31'
        owner: UWQR89ji
        includeNonWorkingDays: true
        timesEstimatedMode: daily
    AddTimesEstimatedResponse:
      description: 'The result of add estimated time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        data:
          type: object
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
          data:
            hours: 1
            startDate: '2023-01-01'
            endDate: '2023-01-31'
            owner: UWQR89ji
            includeNonWorkingDays: true
            timesEstimatedMode: daily
    UpdateTimesEstimatedRequest:
      description: 'The request of update estimated time'
      type: object
      properties:
        hours:
          type: integer
          description: Estimated time,unit is hour.
        startDate:
          type: string
          description: The start time of spent time,Format is YYYY-MM-DD.
        owner:
          type: object
          description: The owner of spent time.
      example:
        hours: 1
        startDate: '2023-01-02'
        owner: UWQR89ji
    UpdateTimesEstimatedResponse:
      description: 'The result of update estimated time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        data:
          type: object
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
          data:
            hours: 1
            startDate: '2023-01-02'
            endDate: '2023-01-31'
            owner: UWQR89ji
            includeNonWorkingDays: true
            timesEstimatedMode: daily
    DeleteTimesEstimatedResponse:
      description: 'The result of delete estimated time'
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
      example:
        - result: SUCCESS
    $ref: ../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            write:project:issue-timeEstimated: Add, edit, delete issue
            write:project:issue-timeRemaining: Add, edit, delete issue
