openapi: 3.0.1
info:
  title: Issue comments
  version: '1.0'
  description: |
    This resource represents issue comments. Use it to get, create, and delete issue comments.
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /project/issues/{issueID}/comments:
    get:
      summary: Get a list of comments
      operationId: 01-get-a-list-of-issues-comment
      description: Get a list of comments
      security:
        - oauth2:
            - read:project:issue-comment
      parameters:
        - name: issueID
          in: path
          description: The ID of the issue
          required: true
          schema:
            type: string
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCommentSuccessResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
    post:
      summary: Send comment to issue
      operationId: 02-send-issue-comment
      description: Send comment to issue
      security:
        - oauth2:
            - write:project:issue-comment
      parameters:
        - name: issueID
          in: path
          description: The ID of the issue
          required: true
          schema:
            type: string
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The comment information to be sent
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCommentRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendCommentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/issues/{issueID}/comments/{commentsID}:
    post:
      summary: Delete comment
      operationId: 03-delete-issue-comment
      description: Delete comment
      security:
        - oauth2:
            - write:project:issue-comment
      parameters:
        - name: issueID
          in: path
          description: The ID of the issue
          required: true
          schema:
            type: string
        - name: commentsID
          in: path
          description: The ID of the comment to be deleted
          required: true
          schema:
            type: string
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCommentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
    put:
      summary: Modify comment information
      operationId: 04-update-issue-comment
      description: Modify comment information
      security:
        - oauth2:
            - write:project:issue-comment
      parameters:
        - name: issueID
          in: path
          description: The ID of the issue
          required: true
          schema:
            type: string
        - name: commentsID
          in: path
          description: The ID of the comment to be modified
          required: true
          schema:
            type: string
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The comment information to be modified
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCommentRequest'
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCommentResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    SendCommentRequest:
      description: The comment information to be sent
      type: object
      properties:
        text:
          maxLength: 128
          minLength: 1
          type: string
          description: Content of comments
        repliedMessageID:
          type: string
          description: The ID of the comment to be replied to
      example:
        text: test-common
        repliedMessageID: asghau87
      required:
        - text
    SendCommentResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
      required:
        - result
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: NotFound
          errorMsg: NotFound IssueComment
        - result: FAIL
          errorCode: NotFound
          errorMsg: NotFound issue
        - result: FAIL
          errorCode: Internal Server Error
          errorMsg: Internal Server Error
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: InvalidParameter Text maximum length of 65535
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: PermissionDenied view_tasks
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: InvalidParameter IssueComment Text Empty
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: InvalidParameter IssueComment Text TooLong
    UpdateCommentRequest:
      description: The comment information to be modified
      type: object
      properties:
        text:
          maxLength: 128
          minLength: 1
          type: string
          description: Content of comments
      example:
        text: test-common
      required:
        - text
    UpdateCommentResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
      required:
        - result
      example:
        - result: SUCCESS
    ListCommentSuccessResponse:
      description: Get a list of comments successfully
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/CommentDetail'
            $ref: ../../../openapi-common/canary/en/paging-query-response-pageInfo-schemas.yaml
      required:
        - result
      example:
        - result: success
          data:
            list:
              - id: hiohi431
                createTime: 1595616876
                owner:
                  id: oin90klo
                  name: owner-name
                text: test-common1
              - id: hiohi432
                createTime: 1595616879
                owner:
                  id: oin90klo
                  name: owner-name
                text: test-common2
            pageInfo:
              count: 1
              endCursor: 5f1b0b3b9c6d4e0001b0b3b9c6d4e000
              hasNextPage: false
              startCursor: 5f1b0b3b9c6d4e0001b0b3b9c6d4e000
              totalCount: 1
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: PermissionDenied super_administrator
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: InvalidParameter limit InvalidType
        - result: FAIL
          errorCode: NotFound
          errorMsg: NotFound issue
        - result: FAIL
          errorCode: Internal Server Error
          errorMsg: Internal Server Error
    CommentDetail:
      type: object
      properties:
        id:
          type: string
          description: The ID of the comment
        createTime:
          type: integer
          description: The time when the comment was created
        owner:
          type: object
          description: The user who commented
          properties:
            id:
              type: string
              description: The ID of the user
            name:
              type: string
              description: The name of the user
        text:
          type: string
          description: Content of comments
    DeleteCommentResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
      required:
        - result
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: MissingParameter teamID
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: MissingParameter issueID
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: MissingParameter user_id
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: MissingParameter commentID
    $ref: ../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            write:project:issue-comment: Add, edit, delete issue comments
            read:project:issue-comment: Access issue comment
