openapi: 3.0.1
info:
  title: Issue operations
  version: '1.0'
  description: |
    This resource represents an action for an issue. Use it to create, move, duplicate and delete issues.
servers:
  - url: https://your-domain/rest/api/v1
  - url: http://your-domain/rest/api/v1
paths:
  /project/publishers/issues/batchDelete:
    post:
      summary: Batch delete issues.
      operationId: 01-batch-delete-issue
      description: Batch delete issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The issues to be deleted.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchDeleteIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchDeleteIssueResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/publishers/issues/batchMove:
    post:
      summary: Batch move issues.
      operationId: 02-batch-move-issue
      description: Batch move issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The issues to be moved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchMoveIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchMoveIssueResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/publishers/issues/batchAdd:
    post:
      summary: Batch create issues.
      operationId: 03-batch-add-issue
      description: Batch create issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The issues to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchAddIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchAddIssueResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/publishers/issues/batchDuplicate:
    post:
      summary: Batch duplicate issues.
      operationId: 04-batch-duplicate-issue
      description: Batch duplicate issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The issues to be duplicated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchDuplicateIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/batchDuplicateIssueResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/issues/{issueID}/Duplicate:
    post:
      summary: Duplicate issue.
      operationId: 05-duplicate-issue
      description: Duplicate issue.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: The issue to be duplicated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DuplicateIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DuplicateIssueResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/issues/batchJobInfo:
    get:
      summary: Get information for batch tasks
      operationId: 06-get-batch-job-info
      description: Get information for batch tasks
      security:
        - oauth2:
            - read:project:issue
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The batch job ID.
        content:
          application/json:
            schema:
              type: object
              properties:
                jobID:
                  type: string
                  description: The batch job ID.
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJobInfoResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    BatchDeleteIssueRequest:
      type: object
      properties:
        issueIDs:
          type: array
          description: The issue IDs to be deleted
          items:
            type: string
    BatchMoveIssueRequest:
      type: object
      properties:
        issueIDs:
          type: array
          description: The issue IDs to be moved
          items:
            type: string
        rules:
          type: array
          description: The rules for moving issues
          items:
            type: object
            properties:
              sourceProjectID:
                type: string
                description: The ID of the project where the issue is located.
              targetProjectID:
                type: string
                description: The ID of the project where the issue will be moved to.
              sourceIssueTypeID:
                type: string
                description: Issue type before moving
              targetIssueTypeID:
                type: string
                description: Issue type after moving
              sourceStatusID:
                type: string
                description: Issue status before moving
              targetStatusID:
                type: string
                description: Issue status after moving
              sourceSubIssueTypeID:
                type: string
                description: Sub-issue type before moving
              targetSubIssueTypeID:
                type: string
                description: Sub-issue type after moving
        issueRelationship:
          type: array
          description: The relationship between issues
          items:
            type: object
            properties:
              id:
                type: string
                description: The ID of the issue
              subIssueIDs:
                type: array
                description: The IDs of the sub-issues
                items:
                  type: string
    BatchAddIssueRequest:
      type: object
      description: The issues to be created.
      properties:
        assignee:
          type: string
          description: The assignee of the issue.
        title:
          type: string
          description: The title of the issue.
        projectID:
          type: string
          description: The ID of the project where the issue will be created.
        issueTypeID:
          type: string
          description: The ID of the issue type.
        fieldValues:
          type: array
          description: The field values of the issue.
          items:
            type: object
            properties:
              fieldID:
                type: string
                description: The ID of the field.
              value:
                type: object
                description: The value of the field.
              type:
                type: string
                description: The type of the field.
        watchers:
          type: array
          description: The watchers of the issue.
          items:
            type: string
            description: The ID of the watcher.
        parentID:
          type: string
          description: The ID of the parent issue.
        timesEstimated:
          type: array
          description: The estimated time of the issue.
          items:
            type: object
            properties:
              owner:
                type: string
                description: The ID of the user who estimates the time.
              hours:
                type: integer
                description: The estimated time.
              includeNonWorkingDays:
                type: boolean
                description: Whether to include non-working days.
              startTime:
                type: string
                description: The start time of the estimated time.
              endTime:
                type: string
                description: The end time of the estimated time.
              timesEstimatedMode:
                type: string
                description: The mode of the estimated time.
    BatchDuplicateIssueRequest:
      type: object
      description: The issues to be duplicated.
      properties:
        issues:
          type: array
          description: The issues to be duplicated.
          items:
            type: object
            properties:
              id:
                type: string
                description: The ID of the issue.
              project:
                type: string
                description: Project ID of the issue.
              issueType:
                type: string
                description: Issue type ID of the issue.
              status:
                type: string
                description: Status to be changed.
        duplicateFields:
          type: array
          description: The fields to be duplicated.
    DuplicateIssueRequest:
      type: object
      description: The issue to be duplicated.
      properties:
        id:
          type: string
          description: The ID of the issue.
        project:
          type: string
          description: Project ID of the issue.
        issueType:
          type: string
          description: Issue type ID of the issue.
        status:
          type: string
          description: Status to be changed.
        copyFields:
          type: array
          description: The fields to be duplicated.
        linkIssue:
          type: object
          description: The issue to be linked.
          properties:
            linkType:
              type: string
              description: The type of the link.
            link_desc_type:
              type: string
              description: The description type of the link.
    DuplicateIssueResponse:
      type: object
      description: The response of the duplicated issue.
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          $ref: '#/components/schemas/IssueDetail'
      required:
        - result
    IssueDetail:
      type: object
      properties:
        assignee:
          type: object
          properties:
            id:
              type: string
              description: ID of the assignee.
            name:
              type: string
              description: Name of the assignee.
        createTime:
          type: integer
          description: CreateTime of the issue.
        dueDate:
          type: string
          description: Issue due date.
        timeEstimatedHour:
          type: integer
          description: Time estimated,unit is hour.
        issueType:
          type: object
          properties:
            id:
              type: string
              description: ID of the issue type.
            name:
              type: string
              description: Name of the issue type.
        title:
          type: string
          description: Title of the issue.
        number:
          type: integer
          description: Number of the issue.
        creator:
          type: object
          properties:
            id:
              type: string
              description: ID of the creator.
            name:
              type: string
              description: Name of the creator.
        parent:
          type: object
          properties:
            id:
              type: string
              description: Parent issue ID.
            title:
              type: string
              description: Parent issue title.
        priority:
          type: object
          properties:
            id:
              type: string
              description: ID of the priority.
            name:
              type: string
              description: Name of the priority.
        project:
          type: object
          properties:
            id:
              type: string
              description: Project ID of the issue.
            name:
              type: string
              description: Project name of the issue.
        timeRemainingHour:
          type: integer
          description: Time remaining,unit is hour.
        sprint:
          type: object
          properties:
            id:
              type: string
              description: ID of the sprint.
            name:
              type: string
              description: Name of the sprint.
        status:
          type: object
          properties:
            id:
              type: string
              description: ID of the status.
            name:
              type: string
              description: Name of the status.
            category:
              type: string
              description: Category of the status.
        subIssueType:
          type: object
          properties:
            id:
              type: string
              description: ID of the sub issue type.
            name:
              type: string
              description: Name of the sub issue type.
        subIssueCount:
          type: integer
          description: Total sub issue.
        subIssueDoneCount:
          type: integer
          description: Total completed sub issue.
        subIssues:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: ID of the sub issue.
              name:
                type: string
                description: Name of the sub issue.
        totalTimeEstimatedHour:
          type: integer
          description: Total time estimated,unit is hour.
        timeSpentHour:
          type: integer
          description: Time spent,unit is hour.
        totalTimeRemainingHour:
          type: integer
          description: Total time remaining,unit is hour.
        id:
          type: string
          description: ID of the issue.
        attachments:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: ID of the attachment.
              name:
                type: string
                description: Name of the attachment.
              createTime:
                type: integer
                description: Create time of the attachment.
    BatchJobInfoResponse:
      type: object
      description: The response of the batch job info.
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          description: The batch job info.
          properties:
            id:
              type: string
              description: The ID of the batch job.
            teamID:
              type: string
              description: The ID of team.
            owner:
              type: string
              description: The creator of the batch tasks.
            status:
              type: string
              description: The status of the batch tasks.
            startTime:
              type: integer
              description: The start time of the batch tasks.
            endTime:
              type: integer
              description: The end time of the batch tasks.
            successful:
              type: integer
              description: The number of successful batch tasks.
            failed:
              type: integer
              description: The number of failed batch tasks.
            unprocessed:
              type: integer
              description: The number of unprocessed batch tasks.
            successfulIssues:
              type: array
              description: The successful batch tasks.
              items:
                type: string
      required:
        - result
    BatchDeleteIssueResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            jobID:
              type: string
              description: Batch task ID
      required:
        - result
      example:
        - result: SUCCESS
          data:
            jobID: 123456
    BatchMoveIssueResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            jobID:
              type: string
              description: Batch task ID
      required:
        - result
      example:
        - result: SUCCESS
          data:
            jobID: 123456
    BatchAddIssueResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            jobID:
              type: string
              description: Batch task ID
      required:
        - result
      example:
        - result: SUCCESS
          data:
            jobID: 123456
    batchDuplicateIssueResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            jobID:
              type: string
              description: Batch task ID
      required:
        - result
      example:
        - result: SUCCESS
          data:
            jobID: 123456
    $ref: ../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://ones.com/oauth2/authorize
          tokenUrl: https://ones.com/oauth2/token
          scopes:
            write:project:issue: 批量关联工作项、取消关联
            read:project:issue: 获取工作项信息
