openapi: 3.0.1
info:
  title: Issue status
  version: '1.0'
  description: |
    This resource represents issue status. Use it to get issue status.
servers:
  - url: https://your-domain/rest/api/v1
  - url: http://your-domain/rest/api/v1
paths:
  /project/issueStatuses:
    get:
      summary: Get a list of issue status
      operationId: get-a-list-of-issue-status
      description: Get a list of issue status.
      security:
        - oauth2:
            - read:project:issueStatus
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
        - $ref: ../../../openapi-common/canary/en/paging-query-request-limit.yaml
        - $ref: ../../../openapi-common/canary/en/paging-query-request-cursor.yaml
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIssueStatusResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    ListIssueStatusResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            list:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: The name of the issue status.
                  id:
                    type: string
                    description: The id of the issue status.
                  createTime:
                    type: integer
                    description: The create time of the issue status.
                  category:
                    type: string
                    description: The category of the issue status.
                  buildIn:
                    type: boolean
                    description: Whether it is a system built-in issue status.
            $ref: ../../../openapi-common/canary/en/paging-query-response-pageInfo-schemas.yaml
      example:
        - result: SUCCESS
          data:
            list:
              - name: 'Not started'
                id: 'oilhiuo9'
                createTime: 1691663955
                category: 'to_do'
                buildIn: true
            pageInfo:
              count: 2
              endCursor: 'sample_end_cursor'
              hasNextPage: false
              startCursor: 'sample_start_cursor'
              totalCount: 2
    $ref: ../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            read:project:issueStatus: Access issue status
