openapi: 3.0.1
info:
  title: Issue attachments
  version: '1.0'
  description: |
    This resource represents issue attachments. Use it to get, create, update, and delete issue attachments.
servers:
  - url: https://your-domain/rest/api/v1
  - url: http://your-domain/rest/api/v1
paths:
  /project/team/{teamID}/issues/{issueID}/attachments:
    get:
      summary: Get attachment list by issueID
      operationId: get-attachment-list-by-issue-id
      description: Get attachment list by issueID
      security:
        - oauth2:
            - read:project:issue-attachment
      parameters:
        - name: teamID
          in: path
          description: The team ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
        - name: fileCreatedTimeSince
          in: query
          description: The start of attachment created time
          schema:
            type: integer
        - name: fileCreatedTimeMax
          in: query
          description: The end of attachment created time
          schema:
            type: integer
        - name: limit
          in: query
          description: The number of data to return
          schema:
            type: integer
        - name: cursor
          in: query
          description: The cursor for pagination
          schema:
            type: string
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIssueAttachmentResponse'
        401:
          description: Returned if the authentication credentials are incorrect or
            missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        403:
          description: Returns if the scope check fails
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        404:
          description: Returned if the resource object was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
    post:
      summary: Upload a file to the issue
      operationId: upload-a-file-to-the-issue
      description: Upload a file to the issue
      security:
        - oauth2:
            - write:project:issue-attachment
      parameters:
        - name: teamID
          in: path
          description: The team ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
                - name
              properties:
                name:
                  maxLength: 64
                  type: string
                  description: The name of file
                description:
                  maxLength: 64
                  type: string
                  description: The description of file
                file:
                  type: string
                  description: The file to upload
                  format: binary
        required: true
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddIssueAttachmentResponse'
        401:
          description: Returned if the authentication credentials are incorrect or
            missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        403:
          description: Returns if the scope check fails
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        404:
          description: Returned if the resource object was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
  /project/team/{teamID}/issues/{issueID}/attachments/{attachmentID}:
    put:
      summary: Update a issue attachment
      operationId: update-a-issue-attachment
      description: Update a issue attachment
      security:
        - oauth2:
            - write:project:issue-attachment
      parameters:
        - name: teamID
          in: path
          description: The team ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
        - name: attachmentID
          in: path
          description: The file ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIssueAttachmentRequest'
        required: true
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateIssueAttachmentResponse'
        401:
          description: Returned if the authentication credentials are incorrect or
            missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        403:
          description: Returns if the scope check fails
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        404:
          description: Returned if the resource object was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
      x-codegen-request-body-name: body
    delete:
      summary: Delete a issue attachment
      operationId: delete-a-issue-attachment
      description: Delete a issue attachment
      security:
        - oauth2:
            - write:project:issue-attachment
      parameters:
        - name: teamID
          in: path
          description: The team ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
        - name: attachmentID
          in: path
          description: The attachment ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSuccessResponse'
        401:
          description: Returned if the authentication credentials are incorrect or
            missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        403:
          description: Returns if the scope check fails
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        404:
          description: Returned if the resource object was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'
components:
  schemas:
    AddIssueAttachmentResponse:
      type: object
      properties:
        result:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
              description: The file ID
            name:
              type: string
              description: The name of file
            hash:
              type: string
              description: The hash of file
            mime:
              type: string
              description: The mime of file
            sizeByte:
              type: integer
              description: The size of file with byte
            url:
              type: string
              description: The url of file
            version:
              type: integer
              description: The version of file
    IssueAttachment:
      type: object
      properties:
        id:
          type: string
          description: The file ID
        name:
          type: string
          description: The name of file
        createTime:
          type: integer
          description: The time when file is uploaded
        creator:
          type: object
          properties:
            id:
              type: string
              description: The ID of people who uploaded file
            name:
              type: string
              description: The name of people who uploaded file
        hash:
          type: string
          description: The hash of file
        mime:
          type: string
          description: The mime of file
        sizeByte:
          type: integer
          description: The size of file with byte
        description:
          type: string
          description: The description of file
    ListIssueAttachmentResponse:
      type: object
      properties:
        result:
          type: string
        data:
          type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/IssueAttachment'
            pageInfo:
              $ref: '#/components/schemas/PageInfo'
    PageInfo:
      type: object
      properties:
        count:
          type: integer
          description: The number of data returned this time.
        endCursor:
          type: string
          description: The last cursor on this page is generally used to turn pages.
            backwards.
        endPos:
          type: integer
          description: The last position on this page.
        hasNextPage:
          type: boolean
          description: Is there a next page.
        startCursor:
          type: string
          description: The first cursor on this page is generally used to turn pages.
            backwards.
        startPos:
          type: integer
          description: The first position on this page.
        totalCount:
          type: integer
          description: The total number of items available in the entire collection,
            including those that are  returned in the current response.
    UpdateIssueAttachmentRequest:
      type: object
      properties:
        name:
          maxLength: 64
          type: string
          description: The file name
        description:
          maxLength: 64
          type: string
          description: The description of file
    UpdateIssueAttachmentResponse:
      type: object
      properties:
        result:
          type: string
    DeleteSuccessResponse:
      type: object
      properties:
        result:
          type: string
    BadResponse:
      type: object
      properties:
        result:
          type: string
          description: The result of this request.
        errorCode:
          type: string
          description: The error code of this request.
        errorMsg:
          type: string
          description: Error message for this request.
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://ones.com/oauth2/authorize
          tokenUrl: https://ones.com/oauth2/token
          scopes:
            read:project:issue-attachment: Access issue attachment information
            write:project:issue-attachment: Add, edit, delete issue attachment
