openapi: 3.0.1
info:
  title: Issue workflows
  version: '1.0'
  description: |
    This resource represents issue workflows. Use it to get, execute issue workflows.
servers:
  - url: https://your-domain/rest/api/v1
  - url: http://your-domain/rest/api/v1
paths:
  /project/team/{teamID}/issues/{issueID}/executable-workflow:
    get:
      summary: Get a list of issue workflows
      operationId: get-a-list-of-issue-workflows
      description: Get a list of issue workflows.
      security:
        - oauth2:
            - read:project:issue-workflow
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllSuccessResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
  /project/team/{teamID}/issues/{issueID}/execute-workflow:
    post:
      summary: Execute workflow for issue
      operationId: execute-workflow-for-issue
      description: Execute workflow for issue.
      security:
        - oauth2:
            - write:project:issue-workflow
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
      requestBody:
        description: The issue workflow information to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteWorkflowRequest'
        required: true
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteWorkflowResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
      x-codegen-request-body-name: body
components:
  schemas:
    ExecuteWorkflowRequest:
      required:
        - id
      type: object
      properties:
        id:
          maxLength: 8
          minLength: 1
          type: string
          description: The id of the issue workflow.
        fieldValues:
          type: array
          description: The fieldValues of the issue field.
          items:
            $ref: '#/components/schemas/FieldValues'
        resources:
          type: array
          description: Attachment ids to be associated, separated by commas.
          items:
            type: object
            properties:
              id:
                type: string
        comment:
          type: array
          description: The comment of the issue.
          items:
            $ref: '#/components/schemas/Comment'
        timeEstimated:
          type: object
          description: The timeEstimated of the issue.
          properties:
            hours:
              type: integer
        timeSpent:
          type: array
          description: The timeSpent of the issue.
          items:
            $ref: '#/components/schemas/TimeSpent'
    TimeSpent:
      required:
        - hours
        - owner
        - startTime
      type: object
      properties:
        owner:
          type: string
          description: The owner of timeSpent.
        startTime:
          type: integer
          description: The startTime of timeSpent.
        hours:
          type: integer
          description: The hours of timeSpent.
        description:
          type: string
          description: The description of timeSpent.
    Comment:
      required:
        - contentType
        - text
      type: object
      properties:
        contentType:
          minimum: 1
          type: integer
          description: The contentType of comment.
        text:
          type: string
          description: The text of comment.
    FieldValues:
      required:
        - fieldID
        - type
        - value
      type: object
      properties:
        fieldID:
          minLength: 8
          type: string
          description: The ID of fieldValue.
        type:
          minimum: 1
          type: integer
          description: The type of fieldValue.
        value:
          type: object
          description: The value of fieldValue.
    ExecuteWorkflowResponse:
      description: The response of execute workflow.
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
      example:
        - result: SUCCESS
    AllSuccessResponse:
      description: The response of get a list of issue workflows.
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the issue workflow.
              id:
                type: string
                description: The id of the issue workflow.
              start:
                type: string
                description: The start state of the issue workflow.
              end:
                type: string
                description: The end state of the issue workflow.
      example:
        - result: SUCCESS
          data:
            - id: '2gUfHXsV'
              name: '关闭'
              start: 'LS1jaMvi'
              end: 'QXSKmnQQ'
    $ref: ../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            read:project:issue-workflow: Access issue workflow
            write:project:issue-workflow: Add, edit, delete issue workflow
