openapi: 3.0.1
info:
  title: Issue attachments
  version: '1.0'
  description: |
    This resource represents issue attachments. Use it to get, create, update, and delete issue attachments.
servers:
  - url: https://your-domain/openapi/v2
  - url: http://your-domain/openapi/v2
paths:
  /project/issues/{issueID}/attachments:
    get:
      summary: Get attachment list by issueID
      operationId: 01-get-attachment-list-by-issue-id
      description: Get attachment list by issueID
      security:
        - oauth2:
            - read:project:issue-attachment
      parameters:
        - $ref: ../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
        - name: fileCreatedTimeSince
          in: query
          description: The start of attachment created time
          schema:
            type: integer
        - name: fileCreatedTimeMax
          in: query
          description: The end of attachment created time
          schema:
            type: integer
        - $ref: ../../../openapi-common/latest/en/paging-query-request-limit.yaml
        - $ref: ../../../openapi-common/latest/en/paging-query-request-cursor.yaml
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIssueAttachmentResponse'
        $ref: ../../../openapi-common/latest/en/no-200-response.yaml
    post:
      summary: Upload a file to the issue
      operationId: 02-upload-a-file-to-the-issue
      description: Upload a file to the issue
      security:
        - oauth2:
            - write:project:issue-attachment
      parameters:
        - $ref: ../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
                - name
              properties:
                name:
                  maxLength: 64
                  type: string
                  description: The name of file
                description:
                  maxLength: 64
                  type: string
                  description: The description of file
                file:
                  type: string
                  description: The file to upload
                  format: binary
        required: true
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddIssueAttachmentResponse'
        $ref: ../../../openapi-common/latest/en/no-200-response.yaml
  /project/issues/{issueID}/attachments/{attachmentID}:
    put:
      summary: Update a issue attachment
      operationId: 03-update-a-issue-attachment
      description: Update a issue attachment
      security:
        - oauth2:
            - write:project:issue-attachment
      parameters:
        - $ref: ../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
        - name: attachmentID
          in: path
          description: The file ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIssueAttachmentRequest'
        required: true
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateIssueAttachmentResponse'
        $ref: ../../../openapi-common/latest/en/no-200-response.yaml
      x-codegen-request-body-name: body
    delete:
      summary: Delete a issue attachment
      operationId: 04-delete-a-issue-attachment
      description: Delete a issue attachment
      security:
        - oauth2:
            - write:project:issue-attachment
      parameters:
        - $ref: ../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID
          required: true
          schema:
            type: string
        - name: attachmentID
          in: path
          description: The attachment ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSuccessResponse'
        $ref: ../../../openapi-common/latest/en/no-200-response.yaml
components:
  schemas:
    AddIssueAttachmentResponse:
      description: The response of add issue attachment
      type: object
      properties:
        $ref: ../../../openapi-common/latest/en/200-response-schemas.yaml
        data:
          type: object
          description: The result of this request.
          properties:
            id:
              type: string
              description: The file ID
            name:
              type: string
              description: The name of file
            hash:
              type: string
              description: The hash of file
            mime:
              type: string
              description: The mime of file
            sizeByte:
              type: integer
              description: The size of file with byte
            url:
              type: string
              description: The url of file
            version:
              type: integer
              description: The version of file
      example:
        - result: SUCCESS
          data:
            id: 5f1b0a3b
            name: 1.png
            hash: 5f1b0a3b5b3b4e0001a3b3b4
            mime: image/png
            sizeByte: 123456
            url: https://xxx.com/1.png
            version: 1
    IssueAttachment:
      description: The issue attachment
      type: object
      properties:
        id:
          type: string
          description: The file ID
        name:
          type: string
          description: The name of file
        createTime:
          type: integer
          description: The time when file is uploaded
        creator:
          type: object
          properties:
            id:
              type: string
              description: The ID of people who uploaded file
            name:
              type: string
              description: The name of people who uploaded file
        hash:
          type: string
          description: The hash of file
        mime:
          type: string
          description: The mime of file
        sizeByte:
          type: integer
          description: The size of file with byte
        description:
          type: string
          description: The description of file
    ListIssueAttachmentResponse:
      description: The response of list issue attachment
      type: object
      properties:
        $ref: ../../../openapi-common/latest/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/IssueAttachment'
            $ref: ../../../openapi-common/latest/en/paging-query-response-pageInfo-schemas.yaml
      example:
        - result: SUCCESS
          data:
            list:
              - id: 5f1b0a3b
                createTime: 1595625600
                name: 1.png
                mime: image/png
                hash: 5f1b0a3b5b3b4e0001a3b3b4
                sizeByte: 123456
                description: 1.png
                creator:
                  id: 5f1b0a32
                  name: 张三
            pageInfo:
              count: 1
              endCursor: eyJ0eXBlIjoiQ3VycmVudCIsIm5hbWUiOiJ0ZXN0IiwidmVyc2lvbiI6IjEuMCIsImNvdW50IjoxLCJzdGFydEN1cnJlbnRDb2RlIjoiNWYxYjBhM2I1YjNiNGUwMDAxYTNiM2I0Iiwic3RhcnRDb2RlIjoiNWYxYjBhM2I1YjNiNGUwMDAxYTNiM2I0Iiwic3RhcnREYXRlIjoiMTU5NTYyNTYwMDAwMCJ9
              hasNextPage: false
              startCursor: eyJ0eXBlIjoiQ3VycmVudCIsIm5hbWUiOiJ0ZXN0IiwidmVyc2lvbiI6IjEuMCIsImNvdW50IjoxLCJzdGFydEN1cnJlbnRDb2RlIjoiNWYxYjBhM2I1YjNiNGUwMDAxYTNiM2I0Iiwic3RhcnRDb2RlIjoiNWYxYjBhM2I1YjNiNGUwMDAxYTNiM2I0Iiwic3RhcnREYXRlIjoiMTU5NTYyNTYwMDAwMCJ9
              totalCount: 1
    UpdateIssueAttachmentRequest:
      description: The request of update issue attachment
      type: object
      properties:
        name:
          maxLength: 64
          type: string
          description: The file name
        description:
          maxLength: 64
          type: string
          description: The description of file
    UpdateIssueAttachmentResponse:
      description: The response of update issue attachment
      type: object
      properties:
        $ref: ../../../openapi-common/latest/en/200-response-schemas.yaml
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: 'NotFound'
          errorMsg: 'NotFound attachment'
    DeleteSuccessResponse:
      description: The response of delete issue attachment
      type: object
      properties:
        $ref: ../../../openapi-common/latest/en/200-response-schemas.yaml
    $ref: ../../../openapi-common/latest/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            read:project:issue-attachment: Access issue attachment information
            write:project:issue-attachment: Add, edit, delete issue attachment
