openapi: 3.0.1
info:
  title: Issue types
  version: '1.0'
  description: |
    This resource represents issue types. Use it to get issue types.
servers:
  - url: https://your-domain/openapi/v2
  - url: http://your-domain/openapi/v2
paths:
  /project/issueTypes:
    get:
      summary: Get a list of issue types
      operationId: get-a-list-of-issue-types
      description: Get a list of issue types.
      security:
        - oauth2:
            - read:project:issueType
      parameters:
        - $ref: ../../../openapi-common/canary/en/request-team.yaml
        - $ref: ../../../openapi-common/canary/en/paging-query-request-limit.yaml
        - $ref: ../../../openapi-common/canary/en/paging-query-request-cursor.yaml
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIssueTypesResponse'
        $ref: ../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    ListIssueTypesResponse:
      type: object
      properties:
        $ref: ../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            list:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the issue type.
                  id:
                    type: string
                    description: ID of the issue type.
                  isSubIssueType:
                    type: boolean
                    description: Is it a child work item type.
                  type:
                    type: string
                    description: Type of the issue type.
                  createTime:
                    type: integer
                    description: CreateTime of the issue type.
                  buildIn:
                    type: boolean
                    description: Whether it is a system built-in work item type.
                  project:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Project name of the issue type.
                      id:
                        type: string
                        description: Project id of the issue type.
            $ref: ../../../openapi-common/canary/en/paging-query-response-pageInfo-schemas.yaml
      example:
        - result: SUCCESS
          data:
            list:
              - name: 'Not started'
                id: 'oilhiuo9'
                createTime: 1691663955
                category: 'to_do'
                buildIn: true
            pageInfo:
              count: 2
              endCursor: 'sample_end_cursor'
              hasNextPage: false
              startCursor: 'sample_start_cursor'
              totalCount: 2
    $ref: ../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            read:project:issueType: Access issue type
