openapi: 3.0.1
info:
  title: Issues
  version: '1.0'
  description: |
    This resource represents issues. Use it to get, create, update, and delete issues.
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /project/publishers/issues:
    post:
      summary: Batch add issues
      operationId: 08-batch-add-issues
      description: Batch add issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
          description: |
            - action: Actions on issue,support `batchAdd`.
        - $ref: ../../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The issues to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchAddIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchAddIssueResponse'
        $ref: ../../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    BatchAddIssueRequest:
      type: object
      description: The issues to be created.
      properties:
        assignee:
          type: string
          description: The assignee of the issue.
        title:
          type: string
          description: The title of the issue.
        projectID:
          type: string
          description: The ID of the project where the issue will be created.
        issueTypeID:
          type: string
          description: The ID of the issue type.
        fieldValues:
          type: array
          description: The field values of the issue.
          items:
            type: object
            properties:
              fieldID:
                type: string
                description: The ID of the field.
              value:
                type: object
                description: The value of the field.
              type:
                type: string
                description: The type of the field.
        watchers:
          type: array
          description: The watchers of the issue.
          items:
            type: string
            description: The ID of the watcher.
        parentID:
          type: string
          description: The ID of the parent issue.
        timesEstimated:
          type: array
          description: The estimated time of the issue.
          items:
            type: object
            properties:
              owner:
                type: string
                description: The ID of the user who estimates the time.
              hours:
                type: integer
                description: The estimated time.
              includeNonWorkingDays:
                type: boolean
                description: Whether to include non-working days.
              startTime:
                type: string
                description: The start time of the estimated time.
              endTime:
                type: string
                description: The end time of the estimated time.
              timesEstimatedMode:
                type: string
                description: The mode of the estimated time.
      example:
        - assignee: 123456
          title: Batch add issue
          projectID: 123456
          issueTypeID: 123456
          fieldValues:
            - fieldID: 123456
              value:
                name: Batch add issue
                id: 123456
              type: single
          watchers:
            - 123456
          parentID: 123456
          timesEstimated:
            - owner: 123456
              hours: 1
              includeNonWorkingDays: true
              startTime: 2020-01-01T00:00:00Z
              endTime: 2020-01-01T00:00:00Z
              timesEstimatedMode: manual
    BatchAddIssueResponse:
      type: object
      properties:
        $ref: ../../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            jobID:
              type: string
              description: Batch issue ID
      required:
        - result
      example:
        - result: SUCCESS
          data:
            jobID: 123456
    $ref: ../../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https:///your-domain/oauth2/authorize
          tokenUrl: https:///your-domain/oauth2/token
          scopes:
            write:project:issue: Add, edit, delete issue
