openapi: 3.0.1
info:
  title: Issues
  version: '1.0'
  description: |
    This resource represents issues. Use it to get, create, update, and delete issues.
servers:
  - url: https://your-domain/rest/api/v1
  - url: http://your-domain/rest/api/v1
paths:
  /project/publishers/issues:
    post:
      summary: Batch delete issues
      operationId: 06-batch-delete-issues
      description: Batch delete issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
          description: |
            - action: Actions on issue,support `batchDelete`.
        - $ref: ../../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The issues to be deleted.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchDeleteIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchDeleteIssueResponse'
        $ref: ../../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    BatchDeleteIssueRequest:
      type: object
      properties:
        issueIDs:
          type: array
          description: The issue IDs to be deleted
          items:
            type: string
    BatchDeleteIssueResponse:
      type: object
      properties:
        $ref: ../../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          properties:
            jobID:
              type: string
              description: Batch issue ID
      required:
        - result
      example:
        - result: SUCCESS
          data:
            jobID: 123456
    $ref: ../../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https:///your-domain/oauth2/authorize
          tokenUrl: https:///your-domain/oauth2/token
          scopes:
            write:project:issue: 批量关联工作项、取消关联
            read:project:issue: 获取工作项信息
