openapi: 3.0.1
info:
  title: Issues
  version: '1.0'
  description: |
    This resource represents issues. Use it to get, create, update, and delete issues.
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /project/issues:
    get:
      summary: Get information for batch issues
      operationId: 11-get-batch-job-info
      description: Get information for batch issues
      security:
        - oauth2:
            - read:project:issue
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
          description: |
            - action: Actions on issue,support `batchJobInfo`.
        - $ref: ../../../../openapi-common/canary/en/request-team.yaml
      requestBody:
        description: The batch job ID.
        content:
          application/json:
            schema:
              type: object
              properties:
                jobID:
                  type: string
                  description: The batch job ID.
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJobInfoResponse'
        $ref: ../../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    BatchJobInfoResponse:
      type: object
      description: The response of the batch job info.
      properties:
        $ref: ../../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          type: object
          description: The batch job info.
          properties:
            id:
              type: string
              description: The ID of the batch job.
            teamID:
              type: string
              description: The ID of team.
            owner:
              type: string
              description: The creator of the batch issues.
            status:
              type: string
              description: The status of the batch issues.
            startTime:
              type: integer
              description: The start time of the batch issues.
            endTime:
              type: integer
              description: The end time of the batch issues.
            successful:
              type: integer
              description: The number of successful batch issues.
            failed:
              type: integer
              description: The number of failed batch issues.
            unprocessed:
              type: integer
              description: The number of unprocessed batch issues.
            successfulIssues:
              type: array
              description: The successful batch issues.
              items:
                type: string
      required:
        - result
    $ref: ../../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https:///your-domain/oauth2/authorize
          tokenUrl: https:///your-domain/oauth2/token
          scopes:
            read:project:issue: Access issue information
