openapi: 3.0.1
info:
  title: Issues
  version: '1.0'
  description: |
    This resource represents issues. Use it to get, create, update, and delete issues.
servers:
  - url: https://your-domain/rest/api/v1
  - url: http://your-domain/rest/api/v1
paths:
  /project/issues/{issueID}:
    post:
      summary: Duplicate issues
      operationId: 10-duplicate-issues
      description: Duplicate issues.
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
          description: |
            - action: Actions on issue,support `duplicate`.
        - $ref: ../../../../openapi-common/canary/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: The issue to be duplicated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DuplicateIssueRequest'
        required: true
      responses:
        200:
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DuplicateIssueResponse'
        $ref: ../../../../openapi-common/canary/en/no-200-response.yaml
components:
  schemas:
    DuplicateIssueRequest:
      type: object
      description: The issue to be duplicated.
      properties:
        id:
          type: string
          description: The ID of the issue.
        project:
          type: string
          description: Project ID of the issue.
        issueType:
          type: string
          description: Issue type ID of the issue.
        status:
          type: string
          description: Status to be changed.
        copyFields:
          type: array
          description: The fields to be duplicated.
        linkIssue:
          type: object
          description: The issue to be linked.
          properties:
            linkType:
              type: string
              description: The type of the link.
            link_desc_type:
              type: string
              description: The description type of the link.
    DuplicateIssueResponse:
      type: object
      description: The response of the duplicated issue.
      properties:
        $ref: ../../../../openapi-common/canary/en/200-response-schemas.yaml
        data:
          $ref: '#/components/schemas/IssueDetail'
      required:
        - result
    IssueDetail:
      type: object
      properties:
        assignee:
          type: object
          properties:
            id:
              type: string
              description: ID of the assignee.
            name:
              type: string
              description: Name of the assignee.
        createTime:
          type: integer
          description: CreateTime of the issue.
        dueDate:
          type: string
          description: Issue due date.
        timeEstimatedHour:
          type: integer
          description: Time estimated,unit is hour.
        issueType:
          type: object
          properties:
            id:
              type: string
              description: ID of the issue type.
            name:
              type: string
              description: Name of the issue type.
        title:
          type: string
          description: Title of the issue.
        number:
          type: integer
          description: Number of the issue.
        creator:
          type: object
          properties:
            id:
              type: string
              description: ID of the creator.
            name:
              type: string
              description: Name of the creator.
        parent:
          type: object
          properties:
            id:
              type: string
              description: Parent issue ID.
            title:
              type: string
              description: Parent issue title.
        priority:
          type: object
          properties:
            id:
              type: string
              description: ID of the priority.
            name:
              type: string
              description: Name of the priority.
        project:
          type: object
          properties:
            id:
              type: string
              description: Project ID of the issue.
            name:
              type: string
              description: Project name of the issue.
        timeRemainingHour:
          type: integer
          description: Time remaining,unit is hour.
        sprint:
          type: object
          properties:
            id:
              type: string
              description: ID of the sprint.
            name:
              type: string
              description: Name of the sprint.
        status:
          type: object
          properties:
            id:
              type: string
              description: ID of the status.
            name:
              type: string
              description: Name of the status.
            category:
              type: string
              description: Category of the status.
        subIssueType:
          type: object
          properties:
            id:
              type: string
              description: ID of the sub issue type.
            name:
              type: string
              description: Name of the sub issue type.
        subIssueCount:
          type: integer
          description: Total sub issue.
        subIssueDoneCount:
          type: integer
          description: Total completed sub issue.
        subIssues:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: ID of the sub issue.
              name:
                type: string
                description: Name of the sub issue.
        totalTimeEstimatedHour:
          type: integer
          description: Total time estimated,unit is hour.
        timeSpentHour:
          type: integer
          description: Time spent,unit is hour.
        totalTimeRemainingHour:
          type: integer
          description: Total time remaining,unit is hour.
        id:
          type: string
          description: ID of the issue.
        attachments:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: ID of the attachment.
              name:
                type: string
                description: Name of the attachment.
              createTime:
                type: integer
                description: Create time of the attachment.
    $ref: ../../../../openapi-common/canary/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https:///your-domain/oauth2/authorize
          tokenUrl: https:///your-domain/oauth2/token
          scopes:
            write:project:issue: Add, edit, delete issue
