name: Deploy Canary
on:
  push:
    branches:
      - next
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  deploy:
    uses: ./.github/workflows/common.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}