name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
        # npm ci 会清空 node_modules，所以缓存需要在 npm ci 之后才运行
      - name: cache node_modules/.cache
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('package-lock.json') }}-${{ github.run_id }}
          path: node_modules/.cache
          restore-keys: ${{ hashFiles('package-lock.json') }}-
      - run: npm run build:dev
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-page # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.