name: publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - uses: alinz/ssh-scp-action@v0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp: -r ./dist/* linhuangdong@120.76.133.46:/data/www
