name: publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )
      - run: eval $(ssh-agent -s)
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
      - run: echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - run: chmod 644 ~/.ssh/known_hosts
      - run: scp -r ./dist/* linhuangdong@120.76.133.46:/data/www
