name: PublicRelease

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      # npm ci 会清空 node_modules，所以缓存需要在 npm ci 之后才运行
      - name: Cache node_modules/.cache
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('package-lock.json') }}-${{ github.run_id }}
          path: node_modules/.cache
          restore-keys: ${{ hashFiles('package-lock.json') }}-

      - run: npm run build

      - name: Build package
        run: |
          tar -czf artifacts.tar.gz -C dist .

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3.4.2
        id: semantic   # Need an `id` for output variables
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 传入 timer 参数，用于 DocSearch 爬虫定时器消费
      - name: Trigger docSearch scraper
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            ${{ github.event.repository.url }}/dispatches \
            -d '{"event_type": "DocSearch","client_payload": { "timer": 14400 }}'